### ISSUE TITLE
error build for postgresql-12

### ISSUE THREAD

**Issue by toplinuxsir** [bluejekyll/pg-extend-rs#105]
centos 7, build for postgresql 12 , error as below:
`
/usr/pgsql-12/include/server/port.h:181:43: warning: format attribute argument not supported: gnu_printf [-Wignored-attributes], err: false
/usr/pgsql-12/include/server/utils/elog.h:155:40: warning: format attribute argument not supported: gnu_printf [-Wignored-attributes], err: false

thread 'main' panicked at 'function not loaded: clang_parseTranslationUnit2', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.26.4/src/lib.rs:1538:1
`

**Comment by bluejekyll** [comment]
can you provide more context please? rust version, pg-extend-rs version (master?), etc...

**Comment by intgr** [comment]
Did you create a `.cargo/config` file in your project as described in the README file?

**Comment by toplinuxsir** [comment]
@intgr Yes , I created
```
[build]
rustflags = "-C link-arg=-undefineddynamic_lookup"

```
@bluejekyll ,
rust version : 1.39.0 pg-extend-rs I cloned from github via below command 
```
git clone  https://github.com/bluejekyll/pg-extend-rs.gi
```
Thanks.

**Comment by toplinuxsir** [comment]
Any advice ? Thanks !

**Comment by bluejekyll** [comment]
I haven't come across the issue that you're running into, though I build against 11 and not 12 locally, but I don't think that's the issue. I think I'd ask how pg is installed on your system, and see if your linker configuration seems sane.

This issue looks like it could be related to the clang version that was used to build/install pg: `clang_parseTranslationUnit2`, vs. what you have locally possibly (if pg came from a binary installation for example).

**Comment by toplinuxsir** [comment]
Which clang version is suitable for buid pg-extend-rs

**Comment by bluejekyll** [comment]
Have you been able to get any of the examples working?

**Comment by toplinuxsir** [comment]
@bluejekyll ， No examples of is working .
But , I change the clang version from 3.4.2 to 7.0 , It works!
Thanks !
