### ISSUE TITLE
Error while building on Windows

### ISSUE THREAD

**Issue by auterium** [bluejekyll/pg-extend-rs#107]
I've been banging my head against the wall for the past 4 hours trying multiple options to make this work and just had no success. While I was able to build the examples under Linux, I simply cannot make it work under Windows.

Here's the error I get:
```sh
--- stdout
cargo:rerun-if-changed=wrapper.h
cargo:rerun-if-env-changed=PG_INCLUDE_PATH

--- stderr
C:\Program Files\PostgreSQL\11\include\server/c.h:77:10: fatal error: 'libintl.h' file not found
C:\Program Files\PostgreSQL\11\include\server/c.h:77:10: fatal error: 'libintl.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', src\libcore\result.rs:1165:5
```

I've tried the following options, all failed:
- Try with PG10 -> same result
- Edit the line in `c.h` to remove `libintl.h` as a dependency -> asks for other dependencies
- Create symlynks for missing files -> after resolving all dependencies, it fails with messages of wrong/non-existing function names in the code

Any help or guidance will be much appreciated! Thanks in advance

**Comment by bluejekyll** [comment]
Oh. It looks like this is on Windows. You might be the first person that’s attempted to get this compiling on Windows.

I personally won’t be much help with that. I know on Ubuntu there’s a specific development install you need for things to compile. Not sure if there’s a similar thing for Windows.

**Comment by bluejekyll** [comment]
My guess is that your missing a system dependency. Have you tried compiling PG from source? If you can get that to work, then I think you’d have better luck with this.

**Comment by auterium** [comment]
Thanks for the quick response! I managed to compile in Ubuntu after installing `postgresql-server-dev-11`, but I can't get it working under Windows. As much as I would prefer to run my experiments on Linux, I must to use a licensed, Windows-only library. I managed to get the lib running from Rust, but I want to try to use it as a PG extension.

I'll try to compile PG from source under Windows, let's see how it goes. I think the problem might be on the include path or something, because all the required files are on the `includes/server` folder, is just that the build process can't find them since they are located in subfolders.

**Comment by auterium** [comment]
A small update after some sleep: I haven't tried to compile PG from source yet, but I tried something else that might sound crazy, but it's shining a bit of light on where the problem might be.

I spawned a Docker container with the PG dev package, installed Rust, cloned this repo, and build one of the examples. Now that I was sure the source files where correct, I copied the full include dir from the container to my Windows machine and tried to build. Since these are not compiled, but just C++ source files, it should work on Windows too, but it doesn't. It's still yielding the same error of missing files (which exists, just on a different location).

My theory with this is that the C++ compiler in Linux has a different include path than the one in Windows. Now, I'm not familiar with C++ compilers (I'm using cygwin64), so if anyone has any idea on how to fix the compiler includepath issue, it would be super helpful.

P.S. once that I get this running in Windows, I'll do a PR on the Readme file to include instructions on it.

**Comment by bluejekyll** [comment]
There are some people that hangout in the discord channel, if you want to join that. It's not super active, but someone there might be able to help?

https://discord.gg/y7ZvY5p

Also, if it's not obvious, building Rust extensions for PG is very similar to how the standard C libraries are built. So any tutorials for building extensions on Windows should translate to using this libraries built here.

**Comment by auterium** [comment]
Thanks @bluejekyll this was VERY helpful. I found this tutorial on building the most basic PG extension in Windows:
https://www.2ndquadrant.com/en/blog/compiling-postgresql-extensions-visual-studio-windows/
The _Include and library directories_ section kinda validates the "hack" I was doing (symlinking the missing header files). I've modified the `pg-extend/build.rs` file to include the missing paths (this replaces lines 41 & 42):
```rust
    let pg_include_win32_msvc = format!("{}\\port\\win32_msvc", pg_include);
    let pg_include_win32 = format!("{}\\port\\win32", pg_include);
    let pg_include_parent = pg_include[..(pg_include.len() - 7)].to_owned();

    let bindings = bindgen::Builder::default()
        .clang_arg(format!("-I{}", pg_include_win32_msvc))
        .clang_arg(format!("-I{}", pg_include_win32))
        .clang_arg(format!("-I{}", pg_include))
        .clang_arg(format!("-I{}", pg_include_parent))
```

With this the compilation process no longer complains about missing header files, but now the error is that the generated `postgres.rs` file has different function signatures than the ones used inside `pg-extend`:
```sh
error[E0425]: cannot find function `siglongjmp` in module `pg_sys`
   --> pg-extend\src\lib.rs:125:25
    |
125 |                 pg_sys::siglongjmp(
    |                         ^^^^^^^^^^ help: a function with a similar name exists: `longjmp`

error[E0412]: cannot find type `sigjmp_buf` in module `pg_sys`
   --> pg-extend\src\lib.rs:150:48
    |
150 |     let original_exception_stack: *mut pg_sys::sigjmp_buf = pg_sys::PG_exception_stack;
    |                                                ^^^^^^^^^^ help: a type alias with a similar name exists: `jmp_buf`

error[E0412]: cannot find type `sigjmp_buf` in module `pg_sys`
   --> pg-extend\src\lib.rs:151:61
    |
151 |     let mut local_exception_stack: mem::MaybeUninit<pg_sys::sigjmp_buf> =
    |                                                             ^^^^^^^^^^ help: a type alias with a similar name exists: `jmp_buf`

error[E0425]: cannot find function `sigsetjmp` in module `pg_sys`
   --> pg-extend\src\lib.rs:153:26
    |
153 |     let jumped = pg_sys::sigsetjmp(
    |                          ^^^^^^^^^ help: a function with a similar name exists: `_setjmp`

error[E0412]: cannot find type `sigjmp_buf` in module `pg_sys`
   --> pg-extend\src\lib.rs:155:60
    |
155 |         local_exception_stack.as_mut_ptr() as *mut pg_sys::sigjmp_buf as *mut _,
    |                                                            ^^^^^^^^^^ help: a type alias with a similar name exists: `jmp_buf`

error[E0588]: packed type cannot transitively contain a `[repr(align)]` type
     --> E:\rust-projects\pg-extend-rs\target\release\build\pg-extend-7be983388aa96263\out/postgres.rs:32283:1
      |
32283 | / pub struct _IMAGE_TLS_DIRECTORY64 {
32284 | |     pub StartAddressOfRawData: ULONGLONG,
32285 | |     pub EndAddressOfRawData: ULONGLONG,
32286 | |     pub AddressOfIndex: ULONGLONG,
...     |
32289 | |     pub __bindgen_anon_1: _IMAGE_TLS_DIRECTORY64__bindgen_ty_1,
32290 | | }
      | |_^

error[E0277]: arrays only have std trait implementations for lengths 0..=32
     --> E:\rust-projects\pg-extend-rs\target\release\build\pg-extend-7be983388aa96263\out/postgres.rs:51634:5
      |
51634 |     pub __bindgen_padding_0: [u8; 40usize],
      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::array::LengthAtMost32` is not implemented for `[u8; 40]`
      |
      = note: required because of the requirements on the impl of `std::fmt::Debug` for `[u8; 40]`
      = note: required because of the requirements on the impl of `std::fmt::Debug` for `&[u8; 40]`
      = note: required for the cast to the object type `dyn std::fmt::Debug`

error: aborting due to 7 previous errors

Some errors have detailed explanations: E0277, E0412, E0425.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `pg-extend`.
```

Thanks again for the help so far. If you can point me to the right direction on how to change these function calls and I make it compile for Windows, I'll gladly send a PR for arch-based conditional compiling

**Comment by auterium** [comment]
After A LOT of wall hitting, I've finally managed to successfully compile in Windows and try out the function from Postgres. I'll prepare a PR with detailed description, but bottomline the issues where:
1. Mismatch of function/var names. There are some naming differences between Windows and Unix-like versions of PG
2. Default binding to Windows API. Current implementation generates bindings for everything in the included space, which in Linux generates a `postgres.rs` file with 32k LoC while in Windows it was generating 138k LoC. Whitelisting the bare minimum stuff generates a 3200 LoC file.
3. Rust flags are different
