### ISSUE TITLE
how to get rows from table? 

### ISSUE THREAD

**Issue by houhanting** [bluejekyll/pg-extend-rs#151]
i'm sorry to trouble u, could u tell me how to get the records from table ? 

for example, i have a table users : 

| id | name | age |  remark  |  
| --- | --- | --- | --- |
1 | bluejjekyll  | 18 | good person |

i want to create a function <strong>get_user_info(id) </strong> which returns the result like: 
```sql
SELECT id, name FROM users WHERE id = :USER_ID:
```

i know we have to use spl , could u tell me how to use it via pg-extend-rs ? 

thank you so much !

**Comment by bluejekyll** [comment]
haha, I like that example. I'm definitely not 18 though ;)

So what you're asking for isn't implemented yet. It requires the SPI (Server Programming Interface) to be abstracted. 

> The Server Programming Interface (SPI) gives writers of user-defined C functions the ability to run SQL commands inside their functions. SPI is a set of interface functions to simplify access to the parser, planner, and executor. SPI also does some memory management.

There's no reason why without a little effort, you couldn't write the FFI bindings for this, but it will take some time and energy.

**Comment by houhanting** [comment]
thank u so much .. ..
