### ISSUE TITLE
Fails to compile on Linux due to mismatched u8

### ISSUE THREAD

**Issue by stillinbeta** [bluejekyll/pg-extend-rs#2]
Environment:
```
$ uname -a
Linux penguin 4.14.67-07156-gc116f2c8c400 #1 SMP PREEMPT Sun Sep 9 14:20:03 PDT 2018 aarch64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
$ cargo version
cargo 1.33.0-nightly (0d1f1bbea 2018-12-19)
```

Errors:
```
error[E0308]: mismatched types
  --> pg-extend/src/lib.rs:68:30
   |
68 |     let args_null: &[bool] = &func_call_info.argnull[..num_args];
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected bool, found u8
   |
   = note: expected type `&[bool]`
              found type `&[u8]`

error[E0308]: mismatched types
  --> pg-extend/src/pg_error.rs:85:12
   |
85 |         if pg_sys::errstart(errlevel, file, line, func_name, ERR_DOMAIN.as_ptr() as *const c_char) {
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected bool, found u8
```

FunctionCallArgsData is defined as:

```rust
pub struct FunctionCallInfoData { pub flinfo : * mut FmgrInfo , pub context : fmNodePtr , pub resultinfo : fmNodePtr , pub fncollation : Oid , pub isnull : bool_ , pub nargs : :: std :: os :: raw :: c_short , pub arg : [ Datum ; 100usize ] , pub argnull : [ bool_ ; 100usize ] , }
```

Where `bool_` is:

```rust
pub type bool_ = :: std :: os :: raw :: c_char ;
```
[Full gist here](https://gist.github.com/881e2086559d0ac5a4a60981cc179eb0)

**Comment by bluejekyll** [comment]
Yes. I ran into this in earlier testing. I was hoping it was a fluke based on my compiler options. Looks like a case We’ll have to handle.

Thanks for the report.

**Comment by stillinbeta** [comment]
@bluejekyll are you working on this? otherwise I'll take a crack at it.

**Comment by bluejekyll** [comment]
Not right at the moment. So please, feel free. My plan was to use `pg_bool::PgBool` to support this. I think that should be change to just carry a standard Rust bool instead of the unknown (until target compile time) postgres bool. Then that that should have a `From<bool_>` and `From<bool>` defined on it. Then in the proc_macro, where the raw bools are being used, first do a `PgBool::from(raw)`, and then `bool::from(pg_bool)` to convert to Rust bool.

At least that was my plan, if you can thing of something better, I'm open.

**Comment by bluejekyll** [comment]
> Sorry, this is my first Rust project.

No worries! This is a little annoying to debug, b/c of the macros, but I'll try and help however I can. :)
