### ISSUE TITLE
Correct Lib Location for Ubuntu 18.04 Postgresql 10

### ISSUE THREAD

**Issue by calben** [bluejekyll/pg-extend-rs#26]
I'm having a terrible time trying to figure out where the `include/server` location is for postgresql installed with `apt install postgresql` on Ubuntu 18.04.
In `/var/lib/` there is no pgsql, but there is a `/var/lib/postgresql/10` which has a `/main` directory that doesn't seem to have any sort of include directory in it.
There's also `/usr/lib/postgresql/10/lib`, but that doesn't seem to be working for me.

What directory should be used for this setup?

Thanks!

**Comment by bluejekyll** [comment]
Sounds like that matches the Travis installation paths. Here’s what we have for the test configuration: 
https://github.com/bluejekyll/pg-extend-rs/blob/master/.travis.yml#L24

**Comment by calben** [comment]
yup, cheers!
