### ISSUE TITLE
Stop relying on panic_handler and remove resume

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/pg-extend-rs#41]
This is an issue with throwing panics across ffi boundaries.

**Comment by jethrogb** [comment]
See https://github.com/rust-lang/rust/issues/58794

**Comment by bluejekyll** [comment]
FYI, this was fixed in #59

**Comment by jethrogb** [comment]
I don't think so?

**Comment by bluejekyll** [comment]
Maybe I misunderstood your concerns before. What’s changed in the library now is that we don’t throw panics across FFI boundaries.

Are you saying that even this isn’t safe?
