### ISSUE TITLE
Over 100 MB of warnings emitted during bindgen build

### ISSUE THREAD

**Issue by intgr** [bluejekyll/pg-extend-rs#47]
When building the `postgres.rs` file generated by bindgen, lots and lots of warnings are emitted like the following:
```
warning: `extern` block uses type `u128` which is not FFI-safe: 128-bit integers don't currently have a known stable ABI
 --> .../target/debug/build/pg-extend-f7ddabc2586f2e23/out/postgres.rs:3:186600
  |
3 | # [ repr ( C ) ] # [ derive ( Copy ...
```

This is annoying because line number 3 contains *all* the code in the generated bindings file, multiplying its size, which results in console output of 183 MB! This can also hide other more relevant warnings.

I couldn't figure out a way to suppress this warning. But I don't understand why all the generated code is on one line, given that bindgen is instructed to use rustfmt:
```
    let bindings = bindgen::Builder::default()
        ...
        .rustfmt_bindings(true)
```

Do you have any idea why this is or should I contact bindgen upstream?

Any idea if there may be other solutions to this issue?

**Comment by bluejekyll** [comment]
Really? I haven’t noticed this. I have disabled a number of warnings, are you using this is some other way than the existing import done in the pg_sys module?

**Comment by intgr** [comment]
Apparently `long double` types are converted to `u128` by bindgen: https://github.com/rust-lang/rust-bindgen/issues/1549

But more curiously, the rustfmt issue only occurs on my macOS laptop. On Linux, the generated `postgres.rs` file is nicely formatted. The warnings are still slightly annoying but not nearly as much:
```
warning: `extern` block uses type `u128` which is not FFI-safe: 128-bit integers don't currently have a known stable ABI
    --> .../pg-extend-rs/target/debug/build/pg-extend-8694441f66e957e2/out/postgres.rs:6502:22
     |
6502 |     pub fn sinl(__x: u128) -> u128;
     |                      ^^^^

warning: `extern` block uses type `u128` which is not FFI-safe: 128-bit integers don't currently have a known stable ABI
    --> .../pg-extend-rs/target/debug/build/pg-extend-8694441f66e957e2/out/postgres.rs:6502:31
     |
6502 |     pub fn sinl(__x: u128) -> u128;
     |                               ^^^^

warning: `extern` block uses type `u128` which is not FFI-safe: 128-bit integers don't currently have a known stable ABI
    --> .../pg-extend-rs/target/debug/build/pg-extend-8694441f66e957e2/out/postgres.rs:6505:24
     |
6505 |     pub fn __sinl(__x: u128) -> u128;
     |                        ^^^^

warning: `extern` block uses type `u128` which is not FFI-safe: 128-bit integers don't currently have a known stable ABI
    --> .../pg-extend-rs/target/debug/build/pg-extend-8694441f66e957e2/out/postgres.rs:6505:33
     |
6505 |     pub fn __sinl(__x: u128) -> u128;
     |                                 ^^^^
```

Not knowing much about bindgen, my question is: why is it even generating stubs for functions that are in the C standard library, not PostgreSQL itself?

**Comment by bluejekyll** [comment]
I’m not actually sure about this. It might be possible to disable libc bindings being generated. The libc crate might be compatible with the bindgen types, but I haven’t done any investigation of this.

**Comment by glandium** [comment]
> But I don't understand why all the generated code is on one line, given that bindgen is instructed to use rustfmt

What likely happens is that you don't have rustfmt installed, or it's not in you $PATH, but bindgen doesn't error out in that case. I had the same issue, fwiw, and filed both #1600 and https://github.com/rust-lang/rust/issues/62999

**Comment by intgr** [comment]
Oh thanks a lot @glandium, that makes sense. This issue can be closed.

**Comment by intgr** [comment]
For the record, link to bindgen issue too: https://github.com/rust-lang/rust-bindgen/issues/1600

**Comment by ldm0** [comment]
You can disable this warning by using:`#[allow(improper_ctypes)]`
