### ISSUE TITLE
setjmp and longjmp should be evaluated and supported

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/pg-extend-rs#56]
Postgres relies on setjmp and longjmp, similar in Rust to Panic. We should come up with a decent way to capture a longjmp from a function that’s executed, when called from Rust and into Postgres, whereby, it would give Rust a chance to clean up any memory or other resources it allocated.

**Comment by eeeebbbbrrrr** [comment]
This might serve as useful information:  https://github.com/rust-lang/rfcs/issues/2625#issuecomment-460141114

**Comment by intgr** [comment]
While working on #50, I realized that logging an ERROR message causes a `longjmp()`, which is not good.

One way of fixing this would be to implement a special case for ERROR messages; like throwing a panic and deferring the logging until the panic handler.

Or are there any cleaner ways to trigger stack unwinding in Rust?

Are there any other `longjmp` hazards that you're worried about besides logging?

**Comment by jamessewell** [comment]
postgres-extend has this:

https://github.com/jeff-davis/postgres-extension.rs/blob/master/src/setjmp.rs

I really think that these two projects could both benefit from merging (at least features).

`pg-extend-rs` has great macro support, `postgres-extension` has a fully working SPI interface, including SPI from BGWorkers, as well as setjmp etc..
